# Generated by Django 4.2 on 2023-04-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('boss', 'BOSS'), ('std', 'Student')], default='std', max_length=60)),
            ],
        ),
    ]
