# Generated by Django 4.2 on 2023-04-12 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_2', '0001_initial'),
        ('app_1', '0002_tuser_description_tuser_tell'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='t',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_2.tposition'),
        ),
    ]
