# Generated by Django 4.2 on 2023-04-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_remove_tuser_t_tuser_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuser',
            name='t',
        ),
    ]
